Spanish language file partially updated
OpenBazaar/OpenBazaar-Client pull request #1828
Opened 2016-11-03 15:22 UTC by r01010010

Didn't test anything

2016-11-03 15:36 UTC, jjeffryes commented
Can you make these updates at https://www.transifex.com/ob1/openbazaar/ instead?

We pull the latest language files from there each time we do an update, that will overwrite any changes made directly in the repo. 

Thank you.

2016-11-03 15:48 UTC, r01010010 commented
Sure!

2016-11-03 16:36 GMT+01:00 Josh Jeffryes <notifications@github.com>:

> Can you make these updates at https://www.transifex.com/ob1/openbazaar/
> instead?
>
> We pull the latest language files from there each time we do an update,
> that will overwrite any changes made directly in the repo.
>
> Thank you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenBazaar/OpenBazaar-Client/pull/1828#issuecomment-258178912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAqqSZzJNO_BVpGpQz5LXreoAzYYs3_aks5q6f9mgaJpZM4Kofhd>
> .
>

2016-11-16 18:05 UTC, jjeffryes requested changes
I noticed one translation that could have a typo in it.

2016-11-16 18:05 UTC, jjeffryes commented on js/languages/es.json
> +    "Welcome": "Bienvenid@",
Should Bienvenid have an at sign at the end of it?

2016-12-14 15:46 UTC, jjeffryes commented
I'm closing this, as it will be overridden by the transifex file.

2016-12-14 15:46 UTC, closed without merging